#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if npx lint-staged; then
  echo "검사 통과"
else
  echo "에러 발생!"
  echo "검사에 실패한 파일 및 코드 라인:"
  # 실패한 파일과 라인 출력
  npx eslint --quiet --format=compact --ext .ts .
fi

